### ISSUE TITLE
Error with build back to April 20th - "The nested type `ConversationSetting' does not exist in the type `Conversation'"

### ISSUE THREAD

**Issue by hyakugei** [isguser/VRAIN#1]
Downloaded via git client - tried the HEAD and also a version from April 20th, but still get the following error:

Assets/InteractionManager/ConversationSettingValue.cs(32,50): error CS0426: The nested type `ConversationSetting' does not exist in the type `Conversation'

**Comment by mahdafr** [comment]
Hello,

Thanks for reporting this issue! The package has been updated and we have corrected the issue. Please re-import the package. Commit version: 1822fff

Thank you,

Mahdokht
